const cropLibrary = [
  { id: "corn", name: "玉米", season: "现在可种", color: "#f6c453", water: 3, note: "至少 12 株成小方阵授粉；株距 30 cm、行距 60 cm。" },
  { id: "luffa", name: "丝瓜", season: "现在可种", color: "#6aa84f", water: 4, note: "需要强支架，放北侧或东侧，避免给番茄辣椒遮阴。" },
  { id: "pea_shoot", name: "豌豆尖", season: "排到秋播", color: "#9bd37a", water: 2, note: "6 月偏热，建议 8 月下旬以后再播。" },
  { id: "yardlong", name: "豇豆", season: "现在可种", color: "#4f9d69", water: 3, note: "喜热，搭 1.8-2 m 支架，风口处绑牢。" },
  { id: "zucchini", name: "西葫芦", season: "现在可种", color: "#7fb069", water: 4, note: "1 株就占约 1 m²，留通风，避开番茄近邻。" },
  { id: "coriander", name: "香菜", season: "少量复播", color: "#8bcf88", water: 2, note: "夏季易抽薹，半阴处每 2 周少量播。" },
  { id: "scallion", name: "葱", season: "现在可种", color: "#a7d676", water: 2, note: "可做床边线，和番茄辣椒兼容。" },
  { id: "water_spinach", name: "空心菜", season: "温暖处试种", color: "#5fbf8f", water: 5, note: "需要高温和稳定水分，可用湿润小区块。" },
  { id: "amaranth", name: "苋菜", season: "现在可种", color: "#b34a68", water: 3, note: "耐热快收，适合和空心菜轮收。" },
  { id: "malabar", name: "豆腐菜", season: "现在可种", color: "#4f8d62", water: 4, note: "喜热可攀援，作为叶菜补位很好。" },
  { id: "fava", name: "蚕豆", season: "秋播/早春", color: "#85b77b", water: 2, note: "6 月不建议新播，留到 9-10 月或明春。" },
  { id: "okra", name: "秋葵", season: "暖位试种", color: "#76a65d", water: 3, note: "法兰克福可试 3-4 株，给最暖、避风、全日照位置。" },
];

const initialBeds = [
  {
    id: 1,
    title: "1号地",
    role: "授粉作物",
    crops: [{ name: "玉米", count: 14, color: "#f6c453" }],
    status: "good",
    water: 54,
    soil: "覆草保湿",
    tasks: ["成小方阵补足授粉", "根部覆盖草屑"],
    note: "玉米需要成块，不要排成单线；北侧留 40 cm 工作边。",
  },
  {
    id: 2,
    title: "2号地",
    role: "攀援豆类",
    crops: [{ name: "豇豆", count: 10, color: "#4f9d69" }],
    status: "watch",
    water: 49,
    soil: "支架待加固",
    tasks: ["搭 2 m A 字架", "傍晚定植后浇透"],
    note: "豇豆喜热，6 月 8 日可播可苗；注意西南风时支架受力。",
  },
  {
    id: 3,
    title: "3号地",
    role: "已购主床",
    crops: [
      { name: "辣椒", count: 8, color: "#e4473d" },
      { name: "番茄", count: 7, color: "#d7372f" },
    ],
    status: "selected",
    water: 58,
    soil: "堆肥+羊毛肥",
    tasks: ["给番茄绑枝", "辣椒侧芽修剪", "检查叶面虫害"],
    note: "番茄与辣椒可相邻，但保持通风；番茄单杆或双杆整枝。",
  },
  {
    id: 4,
    title: "4号地",
    role: "支架与暖位",
    crops: [
      { name: "丝瓜", count: 3, color: "#6aa84f" },
      { name: "秋葵", count: 4, color: "#76a65d" },
    ],
    status: "watch",
    water: 61,
    soil: "高温需求",
    tasks: ["丝瓜架放北边", "秋葵覆黑色地膜升温"],
    note: "丝瓜会很高，支架尽量放北侧，减少对 3 号地遮阴。",
  },
  {
    id: 5,
    title: "5号地",
    role: "夏季叶菜",
    crops: [
      { name: "空心菜", count: 1, color: "#5fbf8f" },
      { name: "苋菜", count: 1, color: "#b34a68" },
      { name: "豆腐菜", count: 1, color: "#4f8d62" },
    ],
    status: "good",
    water: 66,
    soil: "高水分",
    tasks: ["每 10-14 天分批播", "午后热浪加遮阴网"],
    note: "这块作为快收叶菜池，保持湿润但不积水。",
  },
  {
    id: 6,
    title: "6号地",
    role: "南瓜科控制",
    crops: [
      { name: "西葫芦", count: 1, color: "#7fb069" },
      { name: "香菜", count: 1, color: "#8bcf88" },
    ],
    status: "risk",
    water: 44,
    soil: "通风优先",
    tasks: ["只留 1 株西葫芦", "白粉病预防通风"],
    note: "西葫芦占地大，控制在一株；香菜放边缘半阴，少量复播。",
  },
  {
    id: 7,
    title: "7号地",
    role: "秋冬预备",
    crops: [
      { name: "葱", count: 36, color: "#a7d676" },
      { name: "豌豆尖", count: 0, color: "#9bd37a" },
      { name: "蚕豆", count: 0, color: "#85b77b" },
    ],
    status: "good",
    water: 52,
    soil: "轮作缓冲",
    tasks: ["葱做边界线", "8月下旬排豌豆尖", "9月后排蚕豆"],
    note: "现在先用葱和短期叶菜占位，秋天转冷季豆类。",
  },
];

const timeline = [
  { label: "6/8", temp: 18, rain: 7 },
  { label: "6/12", temp: 22, rain: 3 },
  { label: "6/16", temp: 20, rain: 9 },
  { label: "6/20", temp: 24, rain: 2 },
  { label: "6/24", temp: 23, rain: 5 },
  { label: "6/28", temp: 26, rain: 1 },
  { label: "7/2", temp: 25, rain: 4 },
  { label: "7/6", temp: 27, rain: 2 },
];

window.gardenData = { cropLibrary, initialBeds, timeline };
